{% set name = "pymp-pypi" %}
{% set version = "0.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b28bb3b4c7d72ef780ee0a4ad8e4a7b8fab6d65bf9786f6ca503e610918e992

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  commands:
    - pip check
    - python -c "import pymp"
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pymp-pypi/
  summary: This package brings OpenMP-like functionality to Python. It takes the good qualities of OpenMP such as minimal code changes and high efficiency and combines them with the Python Zen of code clarity and ease-of-use.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - classner
